package com.springbootdemo.byb.personaaa.model;

public class personaaa {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.id
     *
     * @mbg.generated Thu Aug 30 18:50:59 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.name
     *
     * @mbg.generated Thu Aug 30 18:50:59 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Person.age
     *
     * @mbg.generated Thu Aug 30 18:50:59 CST 2018
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.id
     *
     * @return the value of Person.id
     *
     * @mbg.generated Thu Aug 30 18:50:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.id
     *
     * @param id the value for Person.id
     *
     * @mbg.generated Thu Aug 30 18:50:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.name
     *
     * @return the value of Person.name
     *
     * @mbg.generated Thu Aug 30 18:50:59 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.name
     *
     * @param name the value for Person.name
     *
     * @mbg.generated Thu Aug 30 18:50:59 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Person.age
     *
     * @return the value of Person.age
     *
     * @mbg.generated Thu Aug 30 18:50:59 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Person.age
     *
     * @param age the value for Person.age
     *
     * @mbg.generated Thu Aug 30 18:50:59 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}